# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(max_length=15),
        ),
    ]
